name: refresh-data-daily
on:
  schedule:
    - cron: '42 0 * * *'

jobs:
  remember-brave-people:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Generate brave people data
        run: >
          ./gradlew dailyRun --scan
          -DaccessKeyId=${{ secrets.AWS_ACCESS_KEY_ID }}
          -DaccessKeySecret=${{ secrets.AWS_ACCESS_KEY_SECRET }}
